import { AppProviders } from "@/components/app-providers";
import { CallManager } from "@/components/CallManager";
import SmoothScrollProvider from "@/components/smooth-scroll-provider";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MConnect",
  description: "Generated by create next app",
  verification: {
    google: "BBx3YaDLfygu4zLmxxSHt7cw45Su4cmhBKbwJDD0kS4",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={` ${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScrollProvider>
            <AppProviders>
              <main>{children}</main>
              <CallManager />
            </AppProviders>
          </SmoothScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
